# Generated by Django 5.2.3 on 2025-06-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='tid',
            new_name='id',
        ),
    ]
