# Generated by Django 5.2.3 on 2025-06-24 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_artistprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), null=True),
        ),
    ]
